config/routes.rb
Rails.application.routes.draw do  
  root to: "pages#home"

  get "problems/new_form", to: "problems#new_form", as: "new_problem_form"
  get "categories/new_name", to: "categories#new_name", as: "new_category_name"
  patch "/users/:id/admin", to: "users#make_admin", as: "make_admin"

  post "/search", to: "pages#search"

  resources :problems
  resources :categories
  resources :users
  
  get "/register", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/emails"
    get "/test", to: "pages#test"
  end
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  include Sluggable
  sluggable_column :title

  validates :title, presence: true, uniqueness: true, length: {minimum: 10}
  validates :description, presence: true, length: {minimum: 20}
  validates :solution, presence: true, length: {minimum: 10}
  validates :category, presence: true
  validates :user, presence: true

  default_scope { order('created_at DESC') }

  belongs_to :category
  belongs_to :user

  def self.search(term)
    return [] if term.blank?
    where("title LIKE ?", "%#{term}%").order(created_at: :desc)
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update, :destroy]

  def index
    @problems = Problem.all
  end

  def show
  end

  def new
    @categories = Category.where(parent_id: nil)
  end

  def new_form
    @category = Category.find_by slug: params[:category]
    @problem = Problem.new(category: @category)
  end

  def create
    @problem = Problem.new(problem_params)
    @problem.category = Category.find_by slug: params[:problem][:category]
    @problem.user = current_user
    if @problem.save
      flash[:success] = "Thanks for sharing!"
      redirect_to problem_path(@problem)
    else
      flash[:danger] = "Invalid input"
      render :new_form
    end
  end

  def edit
  end

  def update
    @category = Category.find_by slug: params[:problem][:category]
    if @problem.update(problem_params) && @problem.update(category: @category)
      flash[:success] = "Changes saved"
      redirect_to problem_path(@problem)
    else
      flash[:danger] = "Invalid input"
      render :edit
    end
  end

  def destroy
    @problem.destroy
    redirect_to problems_path
  end

  private

  def problem_params
    params.require(:problem).permit(:title, :description, :error_message, :solution, :user)
  end

  def set_problem
    @problem = Problem.find_by slug: params[:id]
  end
end

app/views/problems/_form.html.haml
= bootstrap_form_for @problem do |f|
  .row
    .col-sm-4= f.text_field :title, help: "Try to be concise and descriptive"
  .row
    .col-sm-4= f.text_area :description
  .row
    .col-sm-4= f.text_area :error_message, label: "Error Message (optional)"
  .row
    .col-sm-4= f.text_area :solution
  .row
    .col-sm-4= f.text_field :category, value: @problem.category.name, disabled: true
  = f.hidden_field :category, {value: @problem.category.slug}
  
  = f.submit(@problem.new_record? ? "Submit Problem" : "Save Changes", class: "btn btn-primary")

app/views/problems/_problems.html.haml
- problems.each do |problem|
  .problem
    .row
      .col-sm-1
        - parent_icon(problem.category)
      .col-sm-10
        .row
          .col-sm-12
            %span.bold= link_to problem.title, problem_path(problem)
            %span.small= link_to "(#{problem.category.name})", category_path(problem.category)
        .row
          .col-sm-12.small
            Solved #{get_age(problem.created_at)} ago by 
            - if problem.user
              %span= link_to problem.user.username, user_path(problem.user)
            - else
              %span [deleted]
        %hr.pull-left.small

app/views/problems/edit.html.haml
.row
  .col-sm-9
    .h3 Edit Problem
    %hr

= render "form"

app/views/problems/index.html.haml
.row
  .col-sm-9
    .h3 Problems
    %hr
    = render "problems", problems: @problems
  .col-sm-2.col-sm-offset-1
    .h3.pull-right.buttons= link_to "New Problem", new_problem_path, class: "btn btn-lg btn-full btn-primary"

app/views/problems/new.html.haml
.row
  .col-sm-9
    .h3 Submit a Problem
    %hr

Where does your problem belong?
%br
= link_to "Or do you need to make a new category?", new_category_path

%br
%br

.row
  - @categories.each do |category|
    .col-sm-4
      .h4= category.name
      = render "shared/choose_category", category: category

app/views/problems/new_form.html.haml
.row
  .col-sm-9
    .h3 Submit a Problem
    %hr

= render "form"

app/views/problems/show.html.haml
.row
  .col-sm-9
    .h3= @problem.title
    %hr

    .col-sm-offset-1.small 
      Posted to 
      %span= link_to @problem.category.name, category_path(@problem.category) 
      #{get_age(@problem.created_at)} ago, by 
      %span
        - if @problem.user
          = link_to @problem.user.username, user_path(@problem.user)
        - else
          [deleted]

    %br
    %br

    .col-sm-offset-1
      .h4.bold Problem:
      .p= simple_format h(@problem.description)
      %br
      - if !@problem.error_message.blank?
        %a.h4.bold(data-toggle="collapse" href="#error")= "Error Message: (click to show)"
        .p.collapse#error= simple_format h(@problem.error_message)
        .p &nbsp;
      .h3.bold Solution:
      .p= simple_format h(@problem.solution)

  .col-sm-2.col-sm-offset-1
    .h3.pull-right.buttons
      - if @problem.user == current_user
        = link_to "Edit", edit_problem_path(@problem), class: "btn btn-full btn-default"
        = link_to "Delete", problem_path(@problem), method: :delete, class: "btn btn-full btn-default"