config/routes.rb
Rails.application.routes.draw do  
  root to: "pages#home"

  get "problems/new_form", to: "problems#new_form", as: "new_problem_form"
  get "categories/new_name", to: "categories#new_name", as: "new_category_name"
  patch "/users/:id/admin", to: "users#make_admin", as: "make_admin"

  post "/search", to: "pages#search"

  resources :problems
  resources :categories
  resources :users
  
  get "/register", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/emails"
    get "/test", to: "pages#test"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Sluggable
  sluggable_column :username

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true, length: {minimum: 3}
  validates :email, presence: true, uniqueness: true, email: true
  validates :password, presence: true, on: :create, length: {minimum: 5}

  default_scope { order "username" }

  has_many :problems

  def self.search(term)
    return [] if term.blank?
    where("username LIKE ?", "%#{term}%")
  end

  def admin
    role == "admin"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :make_admin, :edit, :update, :destroy]
  before_action :require_admin, only: [:index, :make_admin]
  before_action :require_right_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:info] = "Please log in"
      redirect_to login_path
    else
      flash[:danger] = "Invalid input"
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:info] = "Account updated"
      redirect_to user_path(@user)
    else
      flash[:danger] = "Invalid input"
      render :edit
    end
  end

  def make_admin
    @user.update(role: "admin")
    flash[:success] = "#{@user.username} has been granted admin privileges"
    redirect_to users_path
  end

  def destroy
    if current_user == @user
      session[:user_id] = nil
      @user.destroy
      flash[:success] = "Sorry to see you go"
      redirect_to problems_path
    else
      @user.destroy
      flash[:success] = "User deleted"
      redirect_to users_path
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :role)
  end

  def set_user
    @user = User.find_by slug: params[:id]
  end
end

app/views/users/_form.html.haml
= bootstrap_form_for @user do |f|
  .row
    .col-sm-4= f.text_field :username
  .row
    .col-sm-4= f.email_field :email, label: "Email Address"
  .row
    .col-sm-4= f.password_field :password
  = f.submit(@user.new_record? ? "Create Account" : "Save Changes", class: "btn btn-primary")

app/views/users/edit.html.haml
.row
  .col-sm-9
    .h3 Edit User Account
    %hr

= render "form"

app/views/users/index.html.haml
.row
  .col-sm-9
    .h3 Users
    %hr

%table.table.table-default
  %tr
    %th
    %th Username
    %th Role
    %th Problems
    %th Actions
  - @users.each do |user|
    %tr
      %td
        %span.glyphicon.glyphicon-user
      %td= link_to user.username, user_path(user)
      %td= user.role || "user"
      %td= user.problems.count
      %td
        = link_to "edit", edit_user_path(user), class: "btn btn-xs btn-default" if current_user == user
        = link_to "make admin", make_admin_path(user), class: "btn btn-xs btn-default", method: "patch" if current_user.admin && !user.admin
        = link_to "delete", user_path(user), class: "btn btn-xs btn-default", method: :delete

app/views/users/new.html.haml
.row
  .col-sm-9
    .h3 Register
    %hr

= render "form"

app/views/users/show.html.haml
.row
  .col-sm-9
    .h3= "#{@user.username}'s problems"
    %hr
  .col-sm-2.col-sm-offset-1
    .h3.pull-right.buttons= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-default" if current_user == @user

= render "problems/problems", problems: @user.problems