config/routes.rb
Rails.application.routes.draw do  
  root to: "pages#home"

  get "problems/new_form", to: "problems#new_form", as: "new_problem_form"
  get "categories/new_name", to: "categories#new_name", as: "new_category_name"
  patch "/users/:id/admin", to: "users#make_admin", as: "make_admin"

  post "/search", to: "pages#search"

  resources :problems
  resources :categories
  resources :users
  
  get "/register", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/emails"
    get "/test", to: "pages#test"
  end
end

app/views/pages/home.html.haml
%p Tired of looking for the solution? Already tried rebooting? See if we have it in our 
= link_to "problem database.", problems_path

%br
%br

%p Found a solution to your problem? Want to be a good person and share it? 
= link_to "Sign up", register_path 
or 
= link_to "sign in.", login_path

app/views/pages/search.html.haml
.row
  .col-sm-6
    .h3= "Search for '#{@term}'"
    %hr

%ul.nav.nav-tabs
  %li{:class => ("active" if @obj == "problem")}
    = link_to "Search Problems", search_path(term: @term, obj: "problem"), method: :post
  %li{:class => ("active" if @obj == "category")}
    = link_to "Search Categories", search_path(term: @term, obj: "category"), method: :post
  %li{:class => ("active" if @obj == "user")}
    = link_to "Search Users", search_path(term: @term, obj: "user"), method: :post

%br

%ul
  - case @obj
  - when "problem"
    = "No results" unless @problems.any?
    = render "problems/problems", problems: @problems
  - when "category"
    = "No results" unless @categories.any?
    - @categories.each do |category|
      - unless category.children.any?
        %li= link_to category.name, category_path(category)
  - when "user"
    = "No results" unless @users.any?
    - @users.each do |user|
      %li= link_to user.username, user_path(user)

app/views/pages/test.html.haml
.row
  .col-sm-3
    .list-group#accordion
      - @roots.each do |category|
        %a.list-group-item(data-toggle="collapse" data-parent="#accordion" href="#collapse-#{category.slug}")= category.name
        .collapse.list-group-submenu{:id => "collapse-#{category.slug}"}
          - expand_categories(category)


  / .col-sm-3
  /   .panel-group#accordion
  /     - @roots.each do |category|
  /       .panel.panel-default.accordion-group
  /         .panel-title
  /           %a(data-toggle="collapse" data-parent="#accordion" href="#collapse-#{category.slug}")= category.name
  /           .collapse.panel-collapse{:id => "collapse-#{category.slug}"}
  /             - expand_categories2(category)