config/routes.rb
Rails.application.routes.draw do  
  root to: "pages#home"

  get "problems/new_form", to: "problems#new_form", as: "new_problem_form"
  get "categories/new_name", to: "categories#new_name", as: "new_category_name"
  patch "/users/:id/admin", to: "users#make_admin", as: "make_admin"

  post "/search", to: "pages#search"

  resources :problems
  resources :categories
  resources :users
  
  get "/register", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/emails"
    get "/test", to: "pages#test"
  end
end

app/views/layouts/_messages.html.haml
#messages
  - flash.each do |name, msg|
    %div(class="alert alert-#{name}")
      %a.close(data-dismiss='alert') &#215;
      = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
  - flash.clear

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default#navbar
  .container-fluid
    .navbar-header
      = link_to "TriedRebooting", problems_path, class: "navbar-brand"
    %ul.nav.navbar-nav.navbar-right
      - if logged_in?
        - if current_user.admin
          %li{:class => ("active" if current_page?(users_path))} 
            = link_to "Users", users_path
        %li{:class => ("active" if current_page?(user_path(current_user)))}
          = link_to "My Problems", user_path(current_user)
        %li= link_to "Log Out", logout_path
      - else
        %li{:class => ("active" if current_page?(login_path))}
          = link_to "Sign In", login_path
        %li{:class => ("active" if current_page?(register_path))}
          = link_to "Register", register_path

app/views/layouts/_sidebar.html.haml
#sidebar
  #search
    = bootstrap_form_tag url: "/search", layout: :inline do |f|
      .row
        .col-sm-8= f.text_field :term, hide_label: true, placeholder: "Search..."
        = f.hidden_field :obj, {value: @obj || "problem"}
        .col-sm-4= f.submit "Go", class: "btn btn-warning"

  = link_to "All Categories", categories_path, class: "btn btn-default"
  %br
  
  #accordion.list-group
    - Category.where(parent_id: nil).each do |category|
      %a.list-group-item.bold#root(data-toggle="collapse" data-parent="#accordion" href="#collapse-#{category.slug}")= category.name
      .collapse.list-group-submenu{:id => "collapse-#{category.slug}"}
        - expand_categories_list(category)

app/views/layouts/application.html.haml
%html
%head
  %title TriedRebooting
  = stylesheet_link_tag    'application'
  = javascript_include_tag 'application'
  = csrf_meta_tags
  = stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Oxygen'

%body
  .row
    .col-sm-5
      = render "layouts/messages"
    .col-sm-7
      = render 'layouts/navbar'
  .row  
    .col-sm-9
      #content= yield
    .col-sm-3
      = render "layouts/sidebar"